import client from './apollo'
import {
  ALL_ITEMS_QUERY,
  ALL_TAGS_QUERY,
  ADD_ITEM_MUTATION,
  VIEWER_QUERY,
  USER_QUERY,
  LOGOUT_MUTATION,
  SIGNUP_MUTATION,
  LOGIN_MUTATION,
  BORROW_ITEM_MUTATION,
} from './queries'

export default client
export {
  ALL_ITEMS_QUERY,
  ALL_TAGS_QUERY,
  ADD_ITEM_MUTATION,
  VIEWER_QUERY,
  USER_QUERY,
  LOGOUT_MUTATION,
  SIGNUP_MUTATION,
  LOGIN_MUTATION,
  BORROW_ITEM_MUTATION,
}
